version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "github-actions"
    groups:
      checkout-actions:
        patterns:
          - "actions/checkout"
      codeql-actions:
        patterns:
          - "github/codeql-action/*"
      pages-actions:
        patterns:
          - "actions/configure-pages"
          - "actions/jekyll-build-pages"
          - "actions/upload-pages-artifact"
          - "actions/deploy-pages"
    commit-message:
      prefix: "ci(deps)"
      prefix-development: "ci(deps-dev)"
